
# LISTAR PROPRIETÁRIOS
GET http://localhost:3000/api/proprietarios/ HTTP/1.1
Content-Type: application/json
###

#CRIAR PROPRIETÁRIO
POST http://localhost:3000/api/proprietarios/ HTTP/1.1
Content-Type: application/json

{
    "cpf": 111111111,
    "nome": "João Gui",
    "fone": 111,
    "senha": 123
}
###

# EDITAR PROPRIETÁRIO
PUT http://localhost:3000/api/proprietarios/111111111 HTTP/1.1
Content-Type: application/json

{
    "cpf": 111111111,
    "nome": "João Guilherme Oliveira",
    "fone": 111111
}
###

#DELETAR PROPRIETÁRIO
DELETE http://localhost:3000/api/proprietarios/111111111 HTTP/1.1
Content-Type: application/json
###

# --------------------------------------

# LOGIN
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "cpf": 111111111,
  "senha": 123
}
###

# --------------------------------------

# LISTAR VEÍCULOS
GET http://localhost:3000/api/veiculos/ HTTP/1.1
Content-Type: application/json
###

#LISTAR VEÍCULO + PROPRIETÁRIO
GET http://localhost:3000/api/veiculos/proprietario HTTP/1.1
Content-Type: application/json
Authorization: Bearer SEU_TOKEN_JWT_AQUI
###

# ADD VEÍCULOS
POST http://localhost:3000/api/veiculos/
Content-Type: application/json

{
  "placa": "ABC1234",
  "modelo": "Ferrari",
  "preco": 250000,
  "proprietario": 111111111
}
###

# ATUALIZAR INFO VEICULOS
PUT http://localhost:3000/api/veiculos/3
Content-Type: application/json

{
  "modelo": "Fusca 2.0",
  "preco": 20000000
}

###
