
# LISTAR PROPRIETÁRIOS
GET http://localhost:3000/api/proprietarios/ HTTP/1.1
Content-Type: application/json
###

#CRIAR PROPRIETÁRIO
POST http://localhost:3000/api/proprietarios/ HTTP/1.1
Content-Type: application/json

{
    "cpf": 22222,
    "nome": "Mari",
    "fone": 111,
    "senha": "bbb"
}
###

# EDITAR PROPRIETÁRIO
PUT http://localhost:3000/api/proprietarios/111111111 HTTP/1.1
Content-Type: application/json

{
    "cpf": 111111111,
    "nome": "João Guilherme Oliveira",
    "senha": "456"
}
###

#DELETAR PROPRIETÁRIO
DELETE http://localhost:3000/api/proprietarios/111111111 HTTP/1.1
Content-Type: application/json
###

# --------------------------------------

# LOGIN
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "cpf": 22222,
  "senha": "bbb"
}
###

# --------------------------------------

# LISTAR VEÍCULOS
GET http://localhost:3000/api/veiculos/ HTTP/1.1
Content-Type: application/json
###

#LISTAR VEÍCULOS POR PROPRIETÁRIO LOGADO
GET http://localhost:3000/api/veiculos/proprietario HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcGYiOjIyMjIyLCJpYXQiOjE3MTkyNTQ3ODYsImV4cCI6MTcxOTI1ODM4Nn0.3LjnqYR6stCz0ikSMeBfd6j9twTZPInhl2hgp4OF0o8
###

# ADD VEÍCULOS
POST http://localhost:3000/api/veiculos/
Content-Type: application/json

{
  "placa": "DEF1234",
  "modelo": "Fusca",
  "preco": 100000,
  "proprietario": 22222
}
###

# ATUALIZAR INFO VEICULOS
PUT http://localhost:3000/api/veiculos/3
Content-Type: application/json

{
  "placa": "GHI1234",
  "modelo": "Lamborghini",
  "preco": 2000000
}

###

# DELETAR VEÍCULO
DELETE http://localhost:3000/api/veiculos/9 HTTP/1.1
Content-Type: application/json
###
